/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddBackupModal: typeof import('./../components/Backup/AddBackupModal.vue')['default']
    AppMenu: typeof import('./../components/Main/AppMenu.vue')['default']
    AvailableConnectionPaths: typeof import('./../components/Main/AvailableConnectionPaths.vue')['default']
    BackupTask: typeof import('./../components/Backup/BackupTask.vue')['default']
    ConfigManager: typeof import('./../components/Dev/ConfigManager.vue')['default']
    ConnectionJ1: typeof import('./../components/draft/ConnectionJ1.vue')['default']
    ConnectionJ2: typeof import('./../components/draft/ConnectionJ2.vue')['default']
    ConnectionJ3: typeof import('./../components/draft/ConnectionJ3.vue')['default']
    ConnectionNora: typeof import('./../components/draft/ConnectionNora.vue')['default']
    ConnectionPathIndicator: typeof import('./../components/Main/ConnectionPathIndicator.vue')['default']
    ConnectionSection: typeof import('./../components/Main/ConnectionSection.vue')['default']
    CopyButton: typeof import('./../components/CopyButton.vue')['default']
    CurrentConnectionPath: typeof import('./../components/Main/CurrentConnectionPath.vue')['default']
    DeviceItem: typeof import('./../components/Device/DeviceItem.vue')['default']
    DeviceList: typeof import('./../components/Device/DeviceList.vue')['default']
    DeviceManager: typeof import('./../components/Dev/DeviceManager.vue')['default']
    Explore: typeof import('./../components/Main/Explore.vue')['default']
    FindZimaNora: typeof import('./../components/draft/FindZimaNora.vue')['default']
    FindZimaSingle: typeof import('./../components/draft/FindZimaSingle.vue')['default']
    IconCardButton: typeof import('./../components/Main/IconCardButton.vue')['default']
    LeoSelectLable: typeof import('./../components/draft/LeoSelectLable.vue')['default']
    LeoTag: typeof import('./../components/Common/LeoTag.vue')['default']
    ModelBanner: typeof import('./../components/Main/ModelBanner.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectFolder: typeof import('./../components/Backup/SelectFolder.vue')['default']
    Versions: typeof import('./../components/Versions.vue')['default']
    WindowControl: typeof import('./../components/WindowControl.vue')['default']
    WindowsManager: typeof import('./../components/Dev/WindowsManager.vue')['default']
    ZeroTier: typeof import('./../components/Dev/ZeroTier.vue')['default']
    ZeroTierLinuxSetup: typeof import('./../components/ZeroTierLinuxSetup.vue')['default']
    ZimaBackupButton: typeof import('./../components/Main/ExploreButtons/ZimaBackupButton.vue')['default']
    ZimaDevicePath: typeof import('./../components/Common/ZimaDevicePath.vue')['default']
    ZStepItem: typeof import('./../components/Common/ZStepItem.vue')['default']
  }
}
